name: Build

on:
    workflow_dispatch:

env:
    BUILD_DIR: ./dist

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v4
              with:
                  go-version-file: go.mod
                  cache-dependency-path: go.sum

            - name: 🔨 Build executable
              run: go build -ldflags="-s -w" -o $BUILD_EXE_FILE
              env:
                  BUILD_EXE_FILE: ${{ env.BUILD_EXE_FILE }}

            - name: 🚀 Upload executable
              uses: actions/upload-artifact@v3
              with:
                  path: ${{ env.BUILD_DIR }}
