name: Build

on:
    workflow_dispatch:

env:
    BUILD_DIR: ./dist

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v4
              with:
                  go-version-file: go.mod
                  cache-dependency-path: go.sum

            - name: 🔨 Build executables
              run: ./scripts/build.sh

            - name: 🚀 Upload executables
              uses: actions/upload-artifact@v3
              with:
                  path: ${{ env.BUILD_DIR }}
