name: Release

on:
    workflow_dispatch:

permissions:
    contents: write

env:
    BUILD_DIR: ./dist

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v4
              with:
                  go-version-file: go.mod
                  cache-dependency-path: go.sum

            - name: 🔢 Get version
              id: app_version
              run: echo "version=$(./scripts/print-version.sh)" >> $GITHUB_OUTPUT

            - name: 🔎 Check for existing tag
              run: ./scripts/check-tag-not-exists.sh $TAG_NAME
              env:
                  TAG_NAME: v${{ steps.app_version.outputs.version }}

            - name: 🔨 Build executables
              run: ./scripts/build.sh

            - name: 🚀 Upload executables
              uses: ncipollo/release-action@v1
              with:
                  tag: v${{ steps.app_version.outputs.version }}
                  artifacts: ${{ env.BUILD_DIR }}/*
                  generateReleaseNotes: true
                  draft: true
                  artifactErrorsFailBuild: true
