name: Release

on:
    workflow_dispatch:

permissions:
    contents: write

env:
    APP_VERSION: ""
    TAG_NAME: ""
    BUILD_DIR: ./dist

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v4
              with:
                  go-version-file: go.mod
                  cache-dependency-path: go.sum

            - name: 🔢 Get version
              run: |
                  version=$(./scripts/version.sh)
                  echo "APP_VERSION=${version}" >> $GITHUB_ENV
                  echo "TAG_NAME=v${version}" >> $GITHUB_ENV

            - name: 🔎 Check tag availability
              run: ./scripts/tag-available.sh $TAG_NAME

            - name: 🔨 Build executables
              run: ./scripts/build.sh

            - name: 🚀 Upload executables
              uses: ncipollo/release-action@v1
              with:
                  tag: v${{ env.TAG_NAME }}
                  artifacts: ${{ env.BUILD_DIR }}/*
                  generateReleaseNotes: true
                  draft: true
                  artifactErrorsFailBuild: true
